# live system uses redis, switch to files on local
session.save_handler = "files"
session.save_path = ""
# show errors in dev environment
display_errors = On
# this value is active in php.ini
#error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
