FROM solr:5

RUN mkdir -p /opt/solr/server/solr/local_gastro/data \
	&& mkdir -p /opt/solr/server/solr/local_menu/data \
	&& chown solr /opt/solr/server/solr/local_gastro/data /opt/solr/server/solr/local_menu/data
