<?php

require dirname(__DIR__)."/vendor/autoload.php";

$mpdf     = new \Mpdf\Mpdf();
$content  = file_get_contents(__DIR__."/../test.xml");
$laodfile = simplexml_load_string($content, "SimpleXMLElement", 0, "bpmn2", true);
$list     = [];

$test = $_POST['dataName'];

$list = (new \MarcsBlog\ElementCounter)->countElements($list, $laodfile);
$data = '';
//get Attributes
$exclusiveGateways = $list["exclusiveGateway"];

// get Title
$date2 = new Datetime('now');
$date  = date_format($date2, 'd-m-Y');

//$mpdf->SetHeader('Factsheet|Center Text|{PAGENO}');

//$img = '<img src="preva_icon.png" style="width:90px;" />';


// <-- HEADER -->
$arr = [
	'L'    =>  [
		'content'     => 'Factsheet',
		'font-size'   => 32,
		'font-style'  => 'B',
		'font-family' => 'serif',
		'color'       => '#000000',
	],
	'R'    => ['content' => '<img src="preva_icon.png" style="width:48px; height:48px" />'],

	'C'    =>[
		'content'     => 'generated by Preva on '.date_format($date2, 'm').'. '.date_format($date2, 'd').', '.date_format($date2, 'Y'),
		'font-size'   => 12,
		'font-style'  => 'I',
		'font-family' => 'serif',
		'color'       => '#000000',
	],
	'line' => 1,
];

//$arr['L']['content'] . 'textafter';
$mpdf->SetHeader($arr, 'O');

//$mpdf->WriteHTML(". ");














//   <-- CONTENT -->
$leftCell="border-top: 1px solid #000; border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellBeginning="border-top: 1px solid #000; border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellEnd="border-top: 1px solid #000; padding: 8px; border-collapse: collapse";
$rightCell="border-top: 1px solid #000; border-left: 1px solid #000; padding: 8px; border-collapse: collapse";

$leftCellTh=" padding: 8px; border-right: 1px solid #000; border-collapse: collapse";
$centerCellBeginningTh="border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellEndTh="padding: 8px; border-collapse: collapse";
$rightCellTh="border-left: 1px solid #000; padding: 8px; border-collapse: collapse";

$data .= '<div style="padding-top:20px">
<p style="margin-top:25px"><b>Business process model properties</b></p>
<ul>
	<li style="padding-bottom:8px;">Name: '.$_POST['dataName'].'</li>
	<li>Type:   .bpmn</li>
</ul>
<div style="text-align:center; padding-bottom:30px; padding-top:30px;">
	<img src="process_img_pdf.png" style=" height:300px;" />
</div>
<p style="padding-bottom:8px;"><b>Business process model characteristics</b></p>
<table style="margin-left:auto; width:100%; text-align:center; margin-right:auto;border: 1px solid #000000;">
<tr>
    <th style="'.$leftCellTh.'"><b>Category</b></th>
    <th style="'.$centerCellBeginningTh.'">Metric</th>
    <th style="'.$centerCellEndTh.'">Result</th>
    <th style="'.$rightCellTh.'">Ranking</th>
</tr>
<tr>
    <td style="'.$leftCell.'">Category #1</td>
    <td style="'.$centerCellBeginning.'">ExclusiveGateways</td>
    <td style="'.$centerCellEnd.'">'.$exclusiveGateways.'</td>
    <td style="'.$rightCell.'">%</td>
  </tr>
</table>
</div>';

// <-- FOOTER -->
$mpdf->SetFooter('All rights reserved by Preva');


//$mpdf->WriteHTML(' ', \Mpdf\HTMLParserMode::HTML_BODY, true, false);
$mpdf->WriteHTML($data, \Mpdf\HTMLParserMode::HTML_BODY,);

$mpdf->Output('EstimationResult_'.$test.'_'.$date.'.pdf', 'D');
