<?php
require dirname(__DIR__)."/vendor/autoload.php";
$mpdf = new mPDF();

//$content  = file_get_contents(__DIR__."/../../saves/test");
//$laodfile = simplexml_load_string($content, "SimpleXMLElement", 0, "bpmn2", true);
$list = [];

$test = $_POST['dataName'];

$data = '';
//get Attributes
$filehandler = new \Preva\Io\FileManager();
$process     = $filehandler->load(dirname(__DIR__)."/saves/"."test");

$metricsCalculator = new \Preva\Metric\MetricsCalculator();

if ($process instanceof \Preva\Element\Process) {
	$noa                   = $metricsCalculator->numberOfActivities($process);
	$noac                  = $metricsCalculator->numberOfActivitiesAndControlFlows($process);
	$density               = $metricsCalculator->density($process);
	$separability          = $metricsCalculator->separability($process);
	$sequentiality         = $metricsCalculator->sequentiality($process);
	$diameter              = $metricsCalculator->diameter($process);
	$maxNestingDepth       = $metricsCalculator->maxNestingDepth($process);
	$avgDegreeOfConnectors = $metricsCalculator->avgDegreeOfConnectors($process);
	$maxDegreeOfConnectors = $metricsCalculator->maxDegreeOfConnectors($process);
	$binaryDecisions       = $metricsCalculator->binaryDecisions($process);
	$controlFlowComplexity = $metricsCalculator->controlFlowComplexity($process);
	$concurrency           = $metricsCalculator->concurrency($process);
	$cyclicity             = $metricsCalculator->cyclicity($process);
	$cyclomaticNumber      = $metricsCalculator->cyclomaticNumber($process);
	$cognitiveWeight       = $metricsCalculator->cognitiveWeight($process);
}

// get Title
$date2 = new Datetime('now');
$date  = date_format($date2, 'd-m-Y');

//$mpdf->SetHeader('Factsheet|Center Text|{PAGENO}');

//$img = '<img src="preva_icon.png" style="width:90px;" />';

// <-- HEADER -->
$arr = [
	'L' => [
		'content'     => 'Factsheet',
		'font-size'   => 32,
		'font-style'  => 'B',
		'font-family' => 'serif',
		'color'       => '#000000',
	],
	'R' => ['content' => '<img src="preva_icon.png" style="width:48px; height:48px" />'],

	'C'    => [
		'content'     => 'generated by Preva on '.date_format($date2, 'm').'. '.date_format($date2, 'd').', '.date_format($date2, 'Y'),
		'font-size'   => 12,
		'font-style'  => 'I',
		'font-family' => 'serif',
		'color'       => '#000000',
	],
	'line' => 1,
];

//$arr['L']['content'] . 'textafter';
$mpdf->SetHeader($arr, 'O');

//$mpdf->WriteHTML(". ");

//   <-- CONTENT -->
$leftCell            = "border-top: 1px solid #000; border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellBeginning = "border-top: 1px solid #000; border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellEnd       = "border-top: 1px solid #000; padding: 8px; border-collapse: collapse";
$rightCell           = "border-top: 1px solid #000; border-left: 1px solid #000; padding: 8px; border-collapse: collapse";

$leftCellTh            = " padding: 8px; border-right: 1px solid #000; border-collapse: collapse";
$centerCellBeginningTh = "border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellEndTh       = "padding: 8px; border-collapse: collapse";
$rightCellTh           = "border-left: 1px solid #000; padding: 8px; border-collapse: collapse";
$data                  .= '<div style="padding-top:20px">
<p style="margin-top:25px"><b>Business process model properties</b></p>
<ul>
	<li style="padding-bottom:8px;">Name: '.$_POST['dataName'].'</li>
	<li>Type:   .bpmn</li>
</ul>
<div style="text-align:center; padding-bottom:30px; padding-top:30px;">
	<img src="process_img_pdf.png" style=" height:300px;" />
</div>
<p style="padding-bottom:8px;"><b>Business process model characteristics</b></p>
<table style="margin-left:auto; width:100%; text-align:center; margin-right:auto;border: 1px solid #000000;">
<tr>
    <th style="'.$leftCellTh.'"><b>Category</b></th>
    <th style="'.$centerCellBeginningTh.'">Metric</th>
    <th style="'.$centerCellEndTh.'">Result</th>
    <th style="'.$rightCellTh.'">Ranking</th>
</tr>';

$sizeArray = [
	["name" => "Number of ativities (NOA)", "number" => $noa],
	["name" => "Number of activities control-flow elements (NOAC)", "number" => $noac],
	["name" => "Coefficient of Network Complexity (CNC)", "number" => $noac],
	["name" => "Density", "number" => $density],
];

foreach ($sizeArray as $metric) {
	$data .= '
<tr>
    <td style="'.$leftCell.'">Size</td>
    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
    <td style="'.$rightCell.'">%</td>
  </tr>
';
}
$structureArray = [
	["name" => "Seperability", "number" => $separability],
	["name" => "Sequentiality", "number" => $sequentiality],
	["name" => "Diameter", "number" => $diameter],
];
foreach ($structureArray as $metric) {
	$data .= '
	<tr>
	    <td style="'.$leftCell.'">Structure</td>
	    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
	    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
	    <td style="'.$rightCell.'">%</td>
	  </tr>';
}

$operatorArray = [
	["name" => "Maximum nesting depth", "number" => $maxNestingDepth],
	["name" => "Average degree of connectors", "number" => $avgDegreeOfConnectors],
	["name" => "Maximum degree of Connectors", "number" => $maxDegreeOfConnectors],
	["name" => "Binary decissions", "number" => $binaryDecisions],
	["name" => "Control flow complexity (CFC)", "number" => $controlFlowComplexity],
	["name" => "Concurrency", "number" => $concurrency],
];

foreach ($operatorArray as $metric) {
	$data .= '
	<tr>
	    <td style="'.$leftCell.'">Operator</td>
	    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
	    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
	    <td style="'.$rightCell.'">%</td>
	</tr>';
}

$cognitiveArray = [
	["name" => "Cognitive weigth", "number" => $cognitiveWeight],
];

foreach ($cognitiveArray as $metric) {
	$data .= '
	<tr>
	    <td style="'.$leftCell.'">Cognitive weight</td>
	    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
	    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
	    <td style="'.$rightCell.'">%</td>
	</tr>';
}
$data .= '</table></div>';

// <-- FOOTER -->
$mpdf->SetFooter('All rights reserved by Preva');
$pfad = __DIR__.'../vendor/mpdf/';
var_dump($data);
//$mpdf->WriteHTML(' ', \Mpdf\HTMLParserMode::HTML_BODY, true, false);
$mpdf->WriteHTML($data, HTMLParserMode::HTML_BODY);

$mpdf->Output('EstimationResult_'.$test.'_'.$date.'.pdf', 'D');
