<?php
require dirname(__DIR__)."/vendor/autoload.php";
require dirname(__DIR__)."/vendor/mpdf/mpdf/mpdf.php";

//$mpdf = new mPDF();
$mpdf = new mPDF('utf-8', 'A4', '', '', '15', '15', '16', '30', '9', '20');
$data = '';
//get Attributes
$filehandler = new \Preva\Io\FileManager();
$process     = $filehandler->load(dirname(__DIR__)."/saves/"."test");

$metricsCalculator = new \Preva\Metric\MetricsCalculator();

if ($process instanceof \Preva\Element\Process) {
	$noa                   = $metricsCalculator->numberOfActivities($process);
	$noac                  = $metricsCalculator->numberOfActivitiesAndControlFlows($process);
	$density               = $metricsCalculator->density($process);
	$separability          = $metricsCalculator->separability($process);
	$sequentiality         = $metricsCalculator->sequentiality($process);
	$diameter              = $metricsCalculator->diameter($process);
	$maxNestingDepth       = $metricsCalculator->maxNestingDepth($process);
	$avgDegreeOfConnectors = $metricsCalculator->avgDegreeOfConnectors($process);
	$maxDegreeOfConnectors = $metricsCalculator->maxDegreeOfConnectors($process);
	$binaryDecisions       = $metricsCalculator->binaryDecisions($process);
	$controlFlowComplexity = $metricsCalculator->controlFlowComplexity($process);
	$concurrency           = $metricsCalculator->concurrency($process);
	$cyclicity             = $metricsCalculator->cyclicity($process);
	$cyclomaticNumber      = $metricsCalculator->cyclomaticNumber($process);
	$cognitiveWeight       = $metricsCalculator->cognitiveWeight($process);
}

// get Title
$date2 = new Datetime('now');
$date  = date_format($date2, 'd-m-Y');

//$mpdf->SetHeader('Factsheet|Center Text|{PAGENO}');

$img = '<img src="'.__DIR__.'/preva_icon.png" style="width:90px;" />';


// <-- HEADER -->
$arr                   = [
	'L'    => [
		'content'     => 'Factsheet',
		'font-size'   => 10,
		'font-style'  => 'B',
		'font-family' => 'serif',
		'color'       => '#000000',
	],
	'C'    => [
		'content'     => 'generated by Preva on '.date_format($date2, 'm').'. '.date_format($date2, 'd').', '.date_format($date2, 'Y'),
		'font-size'   => 10,
		'font-style'  => 'I',
		'font-family' => 'serif',
		'color'       => '#000000',
	],
	'R'    => ['content' => '<img src="'.__DIR__.'/preva_icon.jpg" style="width:48px; height:48px" />'],
	'line' => 1,
];
$mpdf->showImageErrors = true;
$mpdf->SetHeader($arr, 'O');
$mpdf->margin_header="3px";

//   <-- CONTENT -->
$leftCell            = "border-top: 1px solid #000; border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellBeginning = "border-top: 1px solid #000; border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellEnd       = "border-top: 1px solid #000; padding: 8px; border-collapse: collapse";
$rightCell           = "border-top: 1px solid #000; border-left: 1px solid #000; padding: 8px; border-collapse: collapse";

$leftCellTh            = " padding: 8px; border-right: 1px solid #000; border-collapse: collapse";
$centerCellBeginningTh = "border-right: 1px solid #000; padding: 8px; border-collapse: collapse";
$centerCellEndTh       = "padding: 8px; border-collapse: collapse";
$rightCellTh           = "border-left: 1px solid #000; padding: 8px; border-collapse: collapse";
$data                  .= '<div style="padding-top:10px">
<p style="margin-top:25px"><b>Business process model properties</b></p>
<div style="padding-bottom:24px; margin-bottom:25px">
	<div style="padding-bottom:8px;">Name: '.$_POST['dataName'].'</div>
	<div>Type:   .bpmn</div>
</div>
<div style="text-align:center; padding-bottom:30px; padding-top:30px; margin-bottom:50px;">
	<img src="'.__DIR__.'/preva_icon.jpg" style="width:300px; height:300px;" />
</div>
<p style="padding-bottom:8px;"><b>Business process model characteristics</b></p>
<table style="width:100%; text-align:center; border: 1px solid #000000;">
<tr>
    <th style="'.$leftCellTh.'"><b>Category</b></th>
    <th style="'.$centerCellBeginningTh.'">Metric</th>
    <th style="'.$centerCellEndTh.'">Result</th>
    <th style="'.$rightCellTh.'">Ranking</th>
</tr>';

$sizeArray = [
	["name" => "Number of ativities (NOA)", "number" => $noa],
	["name" => "Number of activities control-flow elements (NOAC)", "number" => $noac],
	["name" => "Coefficient of Network Complexity (CNC)", "number" => $noac],
	["name" => "Density", "number" => $density],
];

foreach ($sizeArray as $metric) {
	$data .= '
<tr>
    <td style="'.$leftCell.'">Size</td>
    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
    <td style="'.$rightCell.'">%</td>
  </tr>
';
}
$structureArray = [
	["name" => "Seperability", "number" => $separability],
	["name" => "Sequentiality", "number" => $sequentiality],
	["name" => "Diameter", "number" => $diameter],
];
foreach ($structureArray as $metric) {
	$data .= '
	<tr>
	    <td style="'.$leftCell.'">Structure</td>
	    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
	    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
	    <td style="'.$rightCell.'">%</td>
	  </tr>';
}

$operatorArray = [
	["name" => "Maximum nesting depth", "number" => $maxNestingDepth],
	["name" => "Average degree of connectors", "number" => $avgDegreeOfConnectors],
	["name" => "Maximum degree of Connectors", "number" => $maxDegreeOfConnectors],
	["name" => "Binary decissions", "number" => $binaryDecisions],
	["name" => "Control flow complexity (CFC)", "number" => $controlFlowComplexity],
	["name" => "Concurrency", "number" => $concurrency],
];

foreach ($operatorArray as $metric) {
	$data .= '
	<tr>
	    <td style="'.$leftCell.'">Operator</td>
	    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
	    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
	    <td style="'.$rightCell.'">%</td>
	</tr>';
}

$cognitiveArray = [
	["name" => "Cognitive weigth", "number" => $cognitiveWeight],
];

foreach ($cognitiveArray as $metric) {
	$data .= '
	<tr>
	    <td style="'.$leftCell.'">Cognitive weight</td>
	    <td style="'.$centerCellBeginning.'">'.$metric["name"].'</td>
	    <td style="'.$centerCellEnd.'">'.number_format($metric["number"], 2).'</td>
	    <td style="'.$rightCell.'">%</td>
	</tr>';
}
$data .= '</table></div>';
//var_dump($data);
//
// <-- FOOTER -->
$mpdf->SetFooter('All rights reserved by Preva');
//$pfad = __DIR__.'../vendor/mpdf/';
//var_dump($data);
//$mpdf->WriteHTML(' ', \Mpdf\HTMLParserMode::HTML_BODY, true, false);
//$mpdf->WriteHTML($data, HTMLParserMode::HTML_BODY);
//$mpdf->WriteHTML($data, HTMLParserMode::HTML_BODY, true, false);

//try {
$mpdf->WriteHTML($data);
//} catch (MpdfException $e) {
//}
$mpdf->Output('EstimationResult_'.$_POST['dataName'].'_'.$date.'.pdf', 'D');

//$mpdf->Output("reklamacja.pdf", "D");
